kind: pipeline
type: docker
name: drone-cloud-test-for-python3

steps:
- name: backend
    image: python:latest
    commands:
    - pip3 install -r requirements.txt
    - pytest test_app.py
    # - echo ${TEST}

# - name: discord notfication
#     iamge: appleboy/drone-discord
#     settings:
#         webhook_id: ${DISCORD_WEBHOOK_ID}
#         webhook_token: ${DISCORD_WEBHOOK_TOKEN}
#         message: >
#             {{repo.owner}}/{{repo.name}}: {{build.branch}}
#             コメント:
#             {{build.message}}

#             {{#success build.status}}
#             テストをすべて通過しました！おめでとう！
#             {{else}}
#             おっと！テストを通過できなかったようです・・・
#             {{/success}}

      