kind: pipeline
type: docker
name: drone-cloud-test-for-python3

steps:
- name: backend
  image: python:latest
  commands:
  - pip3 install -r requirements.txt
  - pytest test_app.py

steps:
- name: discord
  image: appleboy/drone-discord
  when:
    event: [ push, tag, pull_request ]
    status: [ changed, failure, success ]
  settings:
    webhook_id: 
      from_secret: discord_webhook_id
    webhook_token: 
      from_secret: discord_webhook_token
      message: >
      {{repo.owner}}/{{repo.name}}: {{build.branch}}
      コメント:
      {{build.message}}

      {{#success build.status}}
      テストをすべて通過しました！おめでとう！
      {{else}}
      おっと！テストを通過できなかったようです・・・
      {{/success}}


      