kind: pipeline
type: docker
name: drone-cloud-test-for-python3

steps:
- name: backend
  image: python:latest
  commands:
  - pip3 install -r requirements.txt
  - pytest test_app.py

- name: discord
  image: appleboy/drone-discord
  when:
    event: [ push, tag, pull_request ]
    status: [ changed, failure, success ]
  settings:
    webhook_id: 
      from_secret: discord_webhook_id
    webhook_token: 
      from_secret: discord_webhook_token
    message: test {{repo.owner}}
    
    #   message: >
    #   {{repo.owner}} / {{repo.name}} : {{build.branch}}
    #   コメント:
    #   {{build.message}}

    #   {{#success build.status}}
    #   テストをすべて通過しました！よかったな…で…それが何の役に立つ！
    #   {{else}}
    #   おっと！テストを通過できなかったようです・・・まだまだ心眼が足らぬ。
    #   {{/success}}


      